// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import models "github.com/snowball-devs/backend-utec-inscriptions/models"

// SignupRepository is an autogenerated mock type for the SignupRepository type
type SignupRepository struct {
	mock.Mock
}

// CreateSignup provides a mock function with given fields: ctx, signup
func (_m *SignupRepository) CreateSignup(ctx context.Context, signup *models.Signup) (string, error) {
	ret := _m.Called(ctx, signup)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *models.Signup) string); ok {
		r0 = rf(ctx, signup)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Signup) error); ok {
		r1 = rf(ctx, signup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSignups provides a mock function with given fields: ctx, page
func (_m *SignupRepository) GetSignups(ctx context.Context, page int) ([]models.Signup, error) {
	ret := _m.Called(ctx, page)

	var r0 []models.Signup
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Signup); ok {
		r0 = rf(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Signup)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
